language: php

matrix:
  include:
      - php: 5.6
      - php: 7.0
  fast_finish: true

before_script:
    - "composer install --no-interaction"
    - sed -i 's/short_open_tag = Off/short_open_tag = On/' ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: ant build-travis
